image: ubuntu:trusty

git:
  path: github.com/xysec/irene

script:
  - sudo apt-get update 1> /dev/null 2> /dev/null
  - sudo apt-get -y install node
  - sudo pip install nodeenv
  - nodeenv env
  - source env/bin/activate
  - sudo npm install -g bower ember-cli phantomjs
  - npm install
  - bower install
  - ember test
notify:
  email:
    recipients:
      - dhilipsiva@gmail.com
      - sunny@appknox.com
      - sourav@appknox.com
  webhook:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    username: 'drone'
    channel: '#develop'
    on_started: true
    on_success: true
    on_failure: true
