version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.1.0-stretch-browsers
        environment:
          JOBS: 2
    working_directory: ~/appknox
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-deps-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: NPM Install
          command: npm install
      - save_cache:
          key: v3-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Ember Test
          command: COVERAGE=true npm test
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then

              npm run deploy
              npm run deploy:sequelstring
              npm run deploy:gbm

              curl https://api.rollbar.com/api/1/deploy/ \
                -F access_token=$ROLLBAR_ACCESS_TOKEN \
                -F environment=$ENVIRONMENT \
                -F revision=$REVISION \
                -F local_username=$LOCAL_USERNAME
            fi

            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              npm run deploy:staging
            fi
